language: julia
os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0


notifications:
  email: false

- julia -e 'ENV["PYTHON"] = ""; import Pkg; Pkg.build("PyCall")'


after_success:

- julia -e 'import Pkg; cd(Pkg.dir("UNSflow")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
